services:
  mysql:
    image: mysql:8.0
    container_name: opencharity-mysql
    ports:
      # - "3306:3306"
      - '3307:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - open-charity-network

  redis:
    image: redis:7-alpine
    container_name: opencharity-redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - open-charity-network

volumes:
  mysql-data:
  redis-data:

networks:
  open-charity-network:
    driver: bridge
