FROM node:20-alpine
WORKDIR /app
COPY package.json yarn.lock ./
COPY packages/server/package.json ./packages/server/
RUN yarn install --frozen-lockfile
COPY . .
EXPOSE 3000
CMD ["yarn", "workspace", "server", "dev"]